--  create table
CREATE TABLE NETFLIX_SHOWS
(    show_id  VARCHAR(6),
     type	VARCHAR(10),
	 title	VARCHAR(150),
	 director	VARCHAR(208),
	 casts	VARCHAR(1000),
	 country	VARCHAR(150),
	 date_added	VARCHAR(50),
	 release_year	int,
	 rating	VARCHAR(10),
	 duration	VARCHAR(15),
	 listed_in	VARCHAR(100),
	 description	VARCHAR(250)

);
select * from netflix_shows;

select count(*) as total_content
from netflix_shows;

select distinct type as total_content
from netflix_shows;


-- 15 BUSSINESS PROBLEM
-- Q1 COUNT NUMBER OF MOVIES VS TV SHOWS
SELECT COUNT(*) AS NUMBER_OF_CONTENT, TYPE
FROM NETFLIX_SHOWS
GROUP BY TYPE;

-- Q2 FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS

SELECT TYPE, RATING FROM(
	SELECT COUNT(*) AS NUMBER_OF_CONTENT, TYPE, RATING,
	RANK() OVER(PARTITION BY TYPE ORDER BY COUNT(*) DESC ) AS RANKING
	FROM NETFLIX_SHOWS
	GROUP BY TYPE, RATING
	)AS T1
WHERE RANKING = 1;

-- Q3 LIST ALL MOVIES IN A SPECIFIC YEAR EG(2020)
SELECT * FROM NETFLIX_SHOWS
WHERE TYPE = 'Movie'
AND
RELEASE_YEAR = '2020'
;

-- Q4 FIND THE TOP 5 MOST COUNTRIES WITH MOST CONTENT

SELECT COUNT(SHOW_ID) AS TOTAL_CONTENT,
UNNEST(STRING_TO_ARRAY(COUNTRY,',')) AS NEW_COUNTRY
FROM NETFLIX_SHOWS
GROUP BY 2
ORDER BY 1 DESC
LIMIT 5;

--  Q5 IDENTIFY LONGEST MOVIE
SELECT *
FROM NETFLIX_SHOWS
WHERE TYPE = 'Movie'
and duration = (select max(duration)from netflix_shows)

--  Q6 FIND CONTENT ADDED IN LAST FIVE YEARS

SELECT * FROM NETFLIX_SHOWS
WHERE 
TO_DATE(DATE_ADDED, 'Month DD YYYY')>= CURRENT_DATE - INTERVAL '5 Year'

--  Q7 FIND ALL THE MOVIES AND SHOWS DIRECTED BY 'RAJIV CHILAKA'

SELECT * FROM NETFLIX_SHOWS
WHERE DIRECTOR like '%Rajiv Chilaka%'


-- Q8 LIST ALL TV SHOWS MORE THAN 5 SEASON

SELECT *
FROM NETFLIX_SHOWS
WHERE TYPE = 'TV Show'
and split_part(duration, ' ', 1):: numeric > 5 

 
-- Q9 COUNT NUMBER OF CONTENT OF EACH GENRE

SELECT UNNEST(STRING_TO_ARRAY(LISTED_IN , ',')) AS GENRE,
COUNT(*) 
FROM NETFLIX_SHOWS
GROUP BY 1;


-- Q10 FIND EACH YEAR AND AVG NUMBER OF CONTENT RELEASE BY INDIA ON NETFLIX.
-- RETURN TOP 5 YEAR WITH MAX AVG CONTENT RELEASE

SELECT extract(year from to_date(date_added , 'Month DD YYYY')) as yearly_content,
round(
		count(*)::numeric /( select count(*) as total from netflix_shows
        where country = 'India' ):: numeric * 100 , 2)
		as "avg/year"
from netflix_shows
where country = 'India'
group by 1 

-- Q11  LIST ALL MOVIES THAT ARE DOCUMENTAROY

SELECT * FROM NETFLIX_SHOWS
WHERE TYPE = 'Movie'
and listed_in like '%Documentaries%'

-- Q12 FIND ALL CONTENT WITHOUT DIRECTOR
SELECT * FROM NETFLIX_SHOWS
WHERE DIRECTOR IS NULL

-- Q13 FIND IN HOW MANY MOVIES ACTOR SALMAN KHAN APPEARED IN LAST 10 YEARS
SELECT *
FROM NETFLIX_SHOWS
WHERE  
casts ILIKE '%Salman Khan%'
and release_year > extract(year from  current_date) - 10

-- Q14 FIND TOP 10 ACTORS WHO APPEARED IN MAX NUMBER OF MOVIES PRODUCED IN INDIA
SELECT 
UNNEST(STRING_TO_ARRAY(CASTS, ',')) AS ACTORS,
COUNT(*)
FROM NETFLIX_SHOWS
WHERE COUNTRY like '%India%'
GROUP BY 1
ORDER BY 2 DESC


-- Q15 CATEGORISED THE CONTENT BASSED ON KEYWORDS LIKE "KILL" , "VOILENCE" . and lebled as "GOOD" and  "BAD"
--  COUNT HOW MANY SHOWS FALL IN THIS CATEGORIES


CREATE TABLE NEW_TABLE
AS
(
	SELECT *,
		CASE
			WHEN DESCRIPTION ILIKE '%Kill%' or
		    DESCRIPTION ILIKE '%Voilence%' then  'BAD_CONTENT'
			ELSE  'GOOD_CONTENT'
		END  AS CATEGORY
	FROM NETFLIX_SHOWS
)


SELECT CATEGORY,
COUNT(*)
FROM NEW_TABLE
GROUP BY 1















	


















